small: "64x64"
medium: "100x100"
large: "200x200"
user:
  per_page: 10
product:
  take_rand: 5
  showed_number: 20
  per_page: 10
  take_home: 3
  min_quantity: 1
menu:
  ancestor_number: 4
  child_number: 5
category_id:
  parent: 0
